// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActiveComponentFrame: typeof import('./src/components/UserComponent/ActiveComponentFrame/ActiveComponentFrame.vue')['default']
    AddEvent: typeof import('./src/components/ControlPanel/AddEvent.vue')['default']
    AttrStyle: typeof import('./src/components/ControlPanel/AttrStyle.vue')['default']
    CanvasPage: typeof import('./src/components/EditPageComponent/CanvasPage.vue')['default']
    ComponentDecorator: typeof import('./src/components/UserComponent/ComponentDecorator.vue')['default']
    ComponentPanel: typeof import('./src/components/EditPageComponent/ComponentPanel.vue')['default']
    ComponentResizer: typeof import('./src/components/UserComponent/ActiveComponentFrame/childComps/ComponentResizer.vue')['default']
    ControlPanel: typeof import('./src/components/EditPageComponent/ControlPanel.vue')['default']
    DeleteComponent: typeof import('./src/components/UserComponent/ActiveComponentFrame/childComps/DeleteComponent.vue')['default']
    DialogBox: typeof import('./src/components/EditPageComponent/DialogBox.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    I: typeof import('./src/components/ControlPanel/i.vue')['default']
    Interaction: typeof import('./src/components/ControlPanel/Interaction.vue')['default']
    LogIn: typeof import('./src/components/LoginForm/LogIn.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm/LoginForm.vue')['default']
    LogOn: typeof import('./src/components/LoginForm/LogOn.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProjectEditNav: typeof import('./src/components/EditPageComponent/ProjectEditNav.vue')['default']
    ProjectItem: typeof import('./src/components/ProjectItem.vue')['default']
    ResizeWidget: typeof import('./src/components/UserComponent/ActiveComponentFrame/childComps/ResizeWidget.vue')['default']
    ShowMessage: typeof import('./src/components/ShowMessage/ShowMessage.vue')['default']
    TheRootComponent: typeof import('./src/components/UserComponent/TheRootComponent.vue')['default']
    UserButton: typeof import('./src/components/UserComponent/UserButton.vue')['default']
    UserImage: typeof import('./src/components/UserComponent/UserImage.vue')['default']
    UserLayoutHorizontal: typeof import('./src/components/UserComponent/UserLayoutHorizontal.vue')['default']
    UserLayoutPosition: typeof import('./src/components/UserComponent/UserLayoutPosition.vue')['default']
    UserLayoutVertical: typeof import('./src/components/UserComponent/UserLayoutVertical.vue')['default']
    UserText: typeof import('./src/components/UserComponent/UserText.vue')['default']
  }
}

export { }
